apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
    version: ${VERSION}
    date: ${DATE}
spec:
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
        version: ${VERSION}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${IMAGE}
#          envFrom:
#            - configMapRef:
#                name: shared-configs-terraform
#                optional: true
#            - configMapRef:
#                name: ${SERVICE_NAME}
#                optional: true
#            - configMapRef:
#                name: ${SERVICE_NAME}-terraform
#                optional: true
#            - configMapRef:
#                name: shared-secrets-terraform
#                optional: true
#            - secretRef:
#                name: ${SERVICE_NAME}
#                optional: true
#            - secretRef:
#                name: ${SERVICE_NAME}-terraform
#                optional: true
          ports:
            - name: grpc
              containerPort: 50051
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - grpc-health-probe -addr=:50051
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - grpc-health-probe -addr=:50051
            initialDelaySeconds: 10
            periodSeconds: 5
