apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  ports:
    - name: grpc-50051
      port: 50051
      targetPort: 50051
    - name: http-8080
      port: 8080
      targetPort: 8080
  selector:
    app: ${SERVICE_NAME}
